/*
문제 1

Seattle에 위치한 부서를 제외하고 부서별 월급 평균을 내림차순으로 정리하세요. 
 월급부분은 정수부분까지만 나타내고, '부서명'과 '평균월급'을 컬럼의 이름으로 하세요. */

--1. Seattle에 위치하지 앟은 부서코드들
SELECT DEPARTMENT_ID 
FROM DEPARTMENTS 
WHERE LOCATION_ID != (SELECT LOCATION_ID  FROM LOCATIONS l WHERE CITY = 'Seattle');

--답)
SELECT DEPARTMENT_ID AS "부서명", trunc(avg(e.SALARY)) AS "부셔별 월급 평균"
FROM EMPLOYEES e
WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID 
FROM DEPARTMENTS 
WHERE LOCATION_ID != (SELECT LOCATION_ID  FROM LOCATIONS l WHERE CITY = 'Seattle'))
GROUP BY DEPARTMENT_ID
ORDER BY "부셔별 월급 평균" desc;

/*문제 2

POSTAL_CODE가 5자리 숫자인
각 직원의 전체 이름 (LAST_NAME + FIRST_NAME) , 부서 이름, 도시, 주소를
부서 이름 기준으로 오름차순 정렬, 직원 전체 이름 기준으로 내림차순 정렬하여 출력하세요.
전체이름은 full_name이라는 컬럼으로 하세요.*/

-- 5자리인
SELECT LOCATION_ID,CITY,STREET_ADDRESS  FROM LOCATIONS WHERE REGEXP_LIKE(POSTAL_CODE, '^(\d{5})$');

-- 5자리인 부서 코드들
SELECT DEPARTMENT_ID ,DEPARTMENT_NAME ,CITY,STREET_ADDRESS
FROM DEPARTMENTS JOIN (SELECT LOCATION_ID,CITY,STREET_ADDRESS FROM LOCATIONS WHERE REGEXP_LIKE(POSTAL_CODE, '^(\d{5})$'))l 
ON l.LOCATION_ID = DEPARTMENTS.LOCATION_ID;

-- 답)
SELECT e.FIRST_NAME || e.LAST_NAME AS "full_name" ,d.DEPARTMENT_ID AS "부서코드" , d.DEPARTMENT_NAME AS "부서이름", d.CITY AS "도시" ,d.STREET_ADDRESS AS "주소"
FROM EMPLOYEES e JOIN (SELECT DEPARTMENT_ID ,DEPARTMENT_NAME ,CITY,STREET_ADDRESS
FROM DEPARTMENTS JOIN (SELECT LOCATION_ID,CITY,STREET_ADDRESS FROM LOCATIONS WHERE REGEXP_LIKE(POSTAL_CODE, '^(\d{5})$'))l 
ON l.LOCATION_ID = DEPARTMENTS.LOCATION_ID) d
ON d.DEPARTMENT_ID = e.DEPARTMENT_ID 
ORDER BY "부서이름" ASC, "full_name" desc;


/*문제 3
 * 
Seattle에서 근무하는 2005년 이후에 입사한 사원들의 부서별 평균 급여를 비교하고, 
가장 낮은 평균 급여를 가진 부서를 찾아 그 부서의 모든 사원 목록을 출력하세요.
출력할 컬럼은 아래와 같습니다.*/
--시애들 부서  
SELECT DEPARTMENT_ID 
FROM DEPARTMENTS 
WHERE LOCATION_ID != (SELECT LOCATION_ID  FROM LOCATIONS l WHERE CITY = 'Seattle');

-- 그룹별 평균급여 
SELECT DEPARTMENT_ID, avg(e.SALARY) AS avgsal
FROM EMPLOYEES e 
WHERE e.DEPARTMENT_ID  IN (SELECT DEPARTMENT_ID 
FROM DEPARTMENTS 
WHERE LOCATION_ID != (SELECT LOCATION_ID  FROM LOCATIONS l WHERE CITY = 'Seattle'))
GROUP BY DEPARTMENT_ID
ORDER BY avgsal;

-- 그룹별 평균급여 가장 낮은 평균 급여를 가진 부서id
SELECT a.DEPARTMENT_ID
FROM (
SELECT DEPARTMENT_ID, avg(e.SALARY) AS avgsal
FROM EMPLOYEES e 
WHERE e.DEPARTMENT_ID  IN (SELECT DEPARTMENT_ID 
FROM DEPARTMENTS 
WHERE LOCATION_ID != (SELECT LOCATION_ID  FROM LOCATIONS l WHERE CITY = 'Seattle'))
GROUP BY DEPARTMENT_ID
ORDER BY avgsal)a
WHERE ROWNUM =1;

--답)
SELECT *
FROM EMPLOYEES e 
WHERE e.DEPARTMENT_ID = (SELECT a.DEPARTMENT_ID
FROM (
SELECT DEPARTMENT_ID, avg(e.SALARY) AS avgsal
FROM EMPLOYEES e 
WHERE e.DEPARTMENT_ID  IN (SELECT DEPARTMENT_ID 
FROM DEPARTMENTS 
WHERE LOCATION_ID != (SELECT LOCATION_ID  FROM LOCATIONS l WHERE CITY = 'Seattle'))
GROUP BY DEPARTMENT_ID
ORDER BY avgsal)a
WHERE ROWNUM =1);
